2025-09-17 18:16:03|ERROR|Error.py|16|[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 154, in POST
    Lobby.SendMail(req)
  File "/home/py/share/webcppcluster2025/Lobby.py", line 55, in SendMail
    service.SendSvrd(Config.MAIL_HOST, Config.MAIL_PORT, mailproto.SerializeToString())
  File "/home/py/share/webcppcluster2025/service.py", line 11, in SendSvrd
    tcpCliSock.connect(ADDR)
ConnectionRefusedError: [Errno 111] Connection refused
2025-09-17 18:29:01|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 85, in POST
    res = Account.HandleLogin(userid, session)
  File "/home/py/share/webcppcluster2025/Error.py", line 27, in wrapper
    res = func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 170, in HandleLogin
    print(f"设置前的 session 数据: {session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 18:29:05|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 85, in POST
    res = Account.HandleLogin(userid, session)
  File "/home/py/share/webcppcluster2025/Error.py", line 27, in wrapper
    res = func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 170, in HandleLogin
    print(f"设置前的 session 数据: {session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 18:29:29|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 85, in POST
    res = Account.HandleLogin(userid, session)
  File "/home/py/share/webcppcluster2025/Error.py", line 27, in wrapper
    res = func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 170, in HandleLogin
    print(f"设置前的 session 数据: {session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 18:29:34|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 17, in wrapper
    print(f"Session 数据: {web.config._session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 18:29:54|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 85, in POST
    res = Account.HandleLogin(userid, session)
  File "/home/py/share/webcppcluster2025/Error.py", line 27, in wrapper
    res = func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 170, in HandleLogin
    print(f"设置前的 session 数据: {session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 18:29:54|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 17, in wrapper
    print(f"Session 数据: {web.config._session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 18:30:44|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 85, in POST
    res = Account.HandleLogin(userid, session)
  File "/home/py/share/webcppcluster2025/Error.py", line 27, in wrapper
    res = func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 170, in HandleLogin
    print(f"设置前的 session 数据: {session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 18:30:44|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 17, in wrapper
    print(f"Session 数据: {web.config._session.data}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'data'
2025-09-17 19:07:31|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 85, in POST
    current_session = web.ctx.session
AttributeError: 'ThreadedDict' object has no attribute 'session'
2025-09-17 19:07:41|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 85, in POST
    current_session = web.ctx.session
AttributeError: 'ThreadedDict' object has no attribute 'session'
2025-09-17 19:58:31|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session_id'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 89, in POST
    print(f"DEBUG: 登录前session ID: {current_session.session_id}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_id'
2025-09-17 19:58:36|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session_id'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 17, in wrapper
    print(f"DEBUG: CheckLogin - session ID: {current_session.session_id}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_id'
2025-09-17 19:59:03|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session_id'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 89, in POST
    print(f"DEBUG: 登录前session ID: {current_session.session_id}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_id'
2025-09-17 19:59:09|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session_id'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 17, in wrapper
    print(f"DEBUG: CheckLogin - session ID: {current_session.session_id}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_id'
2025-09-17 19:59:36|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session_id'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 89, in POST
    print(f"DEBUG: 登录前session ID: {current_session.session_id}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_id'
2025-09-17 19:59:36|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session_id'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 17, in wrapper
    print(f"DEBUG: CheckLogin - session ID: {current_session.session_id}")
  File "/home/py/.local/lib/python3.10/site-packages/web/session.py", line 84, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'session_id'
2025-09-17 20:08:37|ERROR|Error.py|16|'_session'
Traceback (most recent call last):
  File "/home/py/.local/lib/python3.10/site-packages/web/utils.py", line 104, in __getattr__
    return self[key]
KeyError: '_session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 82, in POST
    current_session = web.config._session
  File "/home/py/.local/lib/python3.10/site-packages/web/utils.py", line 106, in __getattr__
    raise AttributeError(k)
AttributeError: '_session'
2025-09-17 20:08:37|ERROR|Error.py|16|'_session'
Traceback (most recent call last):
  File "/home/py/.local/lib/python3.10/site-packages/web/utils.py", line 104, in __getattr__
    return self[key]
KeyError: '_session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 16, in wrapper
    current_session = web.config._session
  File "/home/py/.local/lib/python3.10/site-packages/web/utils.py", line 106, in __getattr__
    raise AttributeError(k)
AttributeError: '_session'
2025-09-17 20:10:20|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 82, in POST
    current_session = web.ctx.session
AttributeError: 'ThreadedDict' object has no attribute 'session'
2025-09-17 20:10:20|ERROR|Error.py|16|'ThreadedDict' object has no attribute 'session'
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/Account.py", line 16, in wrapper
    current_session = web.ctx.session
AttributeError: 'ThreadedDict' object has no attribute 'session'
2025-09-17 20:22:58|INFO|app.py|62|SESSION_LOG: {"action": "LOGIN_BEFORE", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:22:58|INFO|app.py|62|SESSION_LOG: {"action": "LOGIN_AFTER", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {"userid": "13800138000"}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:23:05|INFO|Account.py|48|SESSION_LOG: {"action": "CHECK_LOGIN", "userid": null, "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>", "login_status": "not_logged_in"}}
2025-09-17 20:25:23|INFO|app.py|68|SESSION_LOG: {"action": "LOGIN_BEFORE", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:25:23|INFO|app.py|68|SESSION_LOG: {"action": "LOGIN_AFTER", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {"userid": "13800138000"}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:25:24|INFO|Account.py|48|SESSION_LOG: {"action": "CHECK_LOGIN", "userid": null, "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>", "login_status": "not_logged_in"}}
2025-09-17 20:26:11|INFO|app.py|68|SESSION_LOG: {"action": "LOGIN_BEFORE", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:26:11|INFO|app.py|68|SESSION_LOG: {"action": "LOGIN_AFTER", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {"userid": "13800138000"}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:26:13|INFO|Account.py|48|SESSION_LOG: {"action": "CHECK_LOGIN", "userid": null, "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>", "login_status": "not_logged_in"}}
2025-09-17 20:30:03|INFO|app.py|68|SESSION_LOG: {"action": "LOGIN_BEFORE", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:30:03|INFO|app.py|68|SESSION_LOG: {"action": "LOGIN_AFTER", "userid": "13800138000", "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {"userid": "13800138000"}, "additional_info": {"session_type": "<class 'web.session.Session'>"}}
2025-09-17 20:30:12|INFO|Account.py|48|SESSION_LOG: {"action": "CHECK_LOGIN", "userid": null, "client_ip": "127.0.0.1", "session_id": "unknown", "session_data": {}, "additional_info": {"session_type": "<class 'web.session.Session'>", "login_status": "not_logged_in"}}
